[tools]
deno = "latest"
go = "1.24"
julia = "latest"
node = "24.9.0"
"npm:yarn" = "1.22.22"
opam = "latest"
pnpm = "10.14"
uv = "0.7"
"npm:aws-cdk" = "latest"
"npm:mcp-remote" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:@biomejs/biome" = "latest"
lua-language-server = "latest"
stylua = "latest"
"npm:@github/copilot-language-server" = "latest"
