[mgr]  
prepend_keymap = [  
  { on = "<Enter>", run = "plugin smart-enter" },
  { on = "l", run = "plugin smart-enter" },
  { on = "-", run = "leave"},
  { on = ["z", "f"], run = "plugin fzf", desc = "fzf under current directory" },
  { on = ["z", "i"], run = "plugin zoxide", desc = "zoxide" },
  { on = "<C-p>", run = "plugin toggle-pane max-preview" },
  { on = ["<Space>", "g"], run = "shell --block -- lazygit" }
]

[input]  
prepend_keymap = [  
  { on = "<Esc>", run = "close", desc = "Cancel input" }
]
